services:
  mongo:
    image: mongo:7
    container_name: chess-elo-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api:
    image: chess-elo-api
    build:
      context: ../apps/api
    container_name: chess-elo-api
    env_file:
      - ../apps/api/.env
    ports:
      - "8000:8000"
    depends_on:
      - mongo

volumes:
  mongo-data:
