services:
  mongo:
    image: mongo:7
    container_name: chess-elo-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api:
    image: chess-elo-api
    build:
      context: ../apps/api
    container_name: chess-elo-api
    environment:
      CHESS_ELO_MONGODB_URI: mongodb://mongo:27017
      CHESS_ELO_MONGODB_DATABASE: chess_elo
      CHESS_ELO_MONGODB_APP_NAME: chess-elo-api
    ports:
      - "8000:8000"
    depends_on:
      - mongo

volumes:
  mongo-data:
