services:
  mongo:
    image: mongo:7
    container_name: chess-elo-mongo
    ports:
      - "27017:27017"

  api:
    build:
      context: ../apps/api
    container_name: chess-elo-api
    environment:
      CHESS_ELO_MONGODB_URI: mongodb://mongo:27017
      CHESS_ELO_MONGODB_DATABASE: chess_elo
      CHESS_ELO_MONGODB_APP_NAME: chess-elo-api
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  content-web:
    build:
      context: ../apps/content-web
    container_name: chess-elo-content-web
    expose:
      - "4200"
    depends_on:
      - api

  nginx:
    image: nginx:1.27-alpine
    container_name: chess-elo-nginx
    ports:
      - "80:80"
    volumes:
      - ../nginx/content-web.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - content-web
